services:
  kafka:
    image: bitnami/kafka
    restart: unless-stopped
    user: root
    container_name: kafka
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://localhost:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://51.195.102.141:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=ZjRkMzY5NTY4NWVmNDA1YT
      - KAFKA_OPTS=-Djava.security.auth.login.config=/bitnami/jaas/kafka_server_jaas.conf
    volumes:
      - /opt/docker/kafka/bitnami/kafka:/bitnami/kafka
      - /opt/docker/kafka/jaas:/bitnami/jaas
      #- /opt/docker/kafka/config/server.properties:/opt/bitnami/kafka/config/server.properties

# Generate KAFKA_KRAFT_CLUSTER_ID:      -
# cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22
#
#
